### ISSUE TITLE
repair: extent_io.c:603: free_extent_buffer: Assertion `!(eb->flags & 1)' failed.

### ISSUE THREAD

**Issue by kakra** [josefbacik/btrfs-progs#1]
free_extent_buffer dumps core after failing an assertion. It looks like the extent has the dirty flag set.

Thank you for developing a btrfs repair utility.

**Comment by josefbacik** [comment]
I've fixed a bunch of shit today, can you give it another go around and see if it's fixed?

**Comment by kakra** [comment]
I just pulled in your changes... Apparently the problem persists. BTW: I pulled your changes into integration-20111012 from darksatanic because otherwise I get an error about unsupported features:

```
jupiter josefbacik-btrfs-progs [git:master] # ./repair /dev/sdd3
couldn't open because of unsupported option features (8).
Could not open root
```

Anything I can send you for further debugging? The kernel is not able to access some files - it ooopses. That's why I'm trying your repair command - and of course I'd like to support development, btrfs needs a repair command. This is the current output with your latest commits:

```
jupiter btrfs-progs-unstable [git:integration-20111012-josef] # ./repair /dev/sdd3
Bad node blockptr, deleting
Started transid 48653
Bad node blockptr, deleting
Bad node blockptr, deleting
Checking extent root
Bad node blockptr, deleting
[repeated multiple times]
Bad node blockptr, deleting
repair: extent_io.c:603: free_extent_buffer: Assertion `!(eb->flags & 1)' failed.
Abgebrochen (Speicherabzug geschrieben) #<-- core dumped
```

I tried commenting out some of the BUG_ON lines but after a few steps of doing so I reach some BUG_ON lines which I should clearly not comment out.

**Comment by josefbacik** [comment]
run it in gdb and do a bt when that happens so I know where it came from.

**Comment by kakra** [comment]
Well, this seems not very helpful... Strange thing is: when I tried to run it in gdb before I got meaningfull backtraces.

```
(gdb) run
Starting program: /usr/src/btrfs-progs-unstable/repair /dev/sdd3
Bad node blockptr, deleting
Started transid 48660
Bad node blockptr, deleting
Checking extent root
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
Bad node blockptr, deleting
repair: extent_io.c:603: free_extent_buffer: Assertion `!(eb->flags & 1)' failed.

Program received signal SIGABRT, Aborted.
0xb7fde424 in __kernel_vsyscall ()
(gdb) bt
#0  0xb7fde424 in __kernel_vsyscall ()
#1  0xb7e57e08 in raise () from /lib/libc.so.6
#2  0xb7e595b3 in abort () from /lib/libc.so.6
#3  0xb7e50a17 in __assert_fail () from /lib/libc.so.6
#4  0x0806b760 in crc32c_table ()
#5  0x0000025b in ?? ()
#6  0x0806b803 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by kakra** [comment]
Didn't see this problem in a long time...
